#!/usr/bin/env tmux
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# prefix key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
set-option -g allow-passthrough on
set-option -g focus-events on
set -g default-terminal tmux-256color
set -ga terminal-overrides ",xterm-kitty:Tc"
%if "#{==:#{COLORTERM},truecolor}"
    set -as terminal-features ",*-256color:RGB"
%endif
#set-option -g default-shell /opt/homebrew/bin/zsh
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# plugin manager
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor "starlight"

#set -g @plugin '2kabhishek/tmux-tilit'# Optional: defaults to lagoon



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux-nova
# set -g @plugin 'o0th/tmux-nova'
# set -g @nova-nerdfonts true
# set -g @nova-nerdfonts-left 
# set -g @nova-nerdfonts-right 

# set -g @nova-pane-active-border-style "#FFDA00"
# set -g @nova-pane-border-style "#FF6700"
# set -g @nova-status-style-bg "#004266"
# set -g @nova-status-style-fg "#00CFFF"
# set -g @nova-status-style-active-bg "#FFF799"
# set -g @nova-status-style-active-fg "#660000"
# set -g @nova-status-style-double-bg "#262626"

# set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},} ]"

# this is the segment on the left of the bar first color is the bkg and second is the letters or glyphs
# set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
# set -g @nova-segment-mode-colors "#FFDA00 #004266"

# set -g @nova-segment-whoami "#(whoami)@#h"
# set -g @nova-segment-whoami-colors "#FFDA00 #004266"

# set -g @nova-rows 0
# set -g @nova-segments-0-left "mode"
# set -g @nova-segments-0-right "whoami"
# set -g status-left-length 100
# set -g status-right-length 100

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# general settings for tmux pain control
# set -g @plugin 'tmux-plugins/tmux-pain-control'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux sensible settings
# set -g @plugin 'tmux-plugins/tmux-sensible'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux prefix highlight
# set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# set -g @prefix_highlight_fg 'white' # default is 'colour231'
# set -g @prefix_highlight_bg 'blue'  # default is 'colour04'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux which-key
set -g @plugin 'alexwforsythe/tmux-which-key'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux-fzf
# set -g @plugin 'sainnhe/tmux-fzf'
# TMUX_FZF_MENU=\
# "btop\nbtop ~\n"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# tmux resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Run all plugins' scripts
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '${HOME}/.tmux/plugins/tpm/tpm'
